name: i_assistant
description: "Your assistant in daily"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #NAVIGATOR
  go_router: ^8.0.3

  #UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  flutter_slidable: ^3.0.0
  carousel_slider:
    path: ./pubs/slider

  #TEXT
  intl:

  #STATE
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.0.5

  #LOCAL DATA
  shared_preferences: ^2.1.2
  hive:
  hive_flutter:

  #CODE GEN
  json_annotation: ^4.8.1

  #PERMISSIONS
  record: ^5.0.5
  path_provider: ^2.1.3
  path: ^1.9.0

  #AUDIO
  just_audio: ^0.9.38

  #NOTIFICATIONS
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

dev_dependencies:

  #CODE GEN
  build_runner: ^2.4.8
  drift_dev: ^2.11.0
  freezed: ^2.3.5
  json_serializable: ^6.7.1

  #TEST
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  #NATIVE ICONS
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/svg/
    - assets/images/raster/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
